cd castor_experiments/generic_query1
sh run.sh
cd ../generic_query2
sh run.sh
cd ../generic_query3
sh run.sh
cd ../generic_query4
sh run.sh
cd ../generic_query5
sh run.sh
cd ../generic_query6
sh run.sh
cd ../generic_query7
sh run.sh
cd ../generic_query8
sh run.sh
cd ../generic_query9
sh run.sh
cd ../../